### ISSUE TITLE
RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!

### ISSUE THREAD

**Issue by nzuhrah** [alvarobartt/covid-daily#3]
Hi, when I try to retrieve daily chart's data from every country with this code, it appear this kind of error. Can you guide me how to fix it?

```
data = covid_daily.data(country='malaysia', chart='total-currently-infected-linear', as_json=False)

print(data.head())
```

Output:

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-6-6229583a2d0a> in <module>
> ----> 1 data = covid_daily.data(country='malaysia', chart='total-currently-infected-linear', as_json=False)
>       2 
>       3 print(data.head())
> 
> ~\anaconda3\lib\site-packages\covid_daily\covid.py in data(country, chart, as_json)
>     166 
>     167     if not flag:
> --> 168         raise RuntimeError("Information could not be retrieved since it is not available at Worldometers.info!")
>     169 
>     170     return data
> 
> RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!

**Comment by alvarobartt** [comment]
Hi @nzuhrah I've checked the data and it looks available in worldometers.info/coronavirus, I'll test this tomorrow including some flags so as to spot the error and hopefully fix it! 👍🏻

**Comment by OmkarShivaprasad** [comment]
Hi did you find a solution to this?

**Comment by alvarobartt** [comment]
Hi @OmkarShivaprasad I did some fixes some time ago, but I'm not sure whether this is currently fixed or not, can you please check? Thank you! 😄 

BTW if this error still persists, please let me know (share the error code too) so that I can find a way to solve this!

**Comment by proydu** [comment]
Still same error:

RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!

**Comment by kmu2000** [comment]
I got the same error too.

**Comment by BaoshanPang** [comment]
I am geting the same error too for most country except for 'china':
>>> data = covid_daily.data(country='india', chart='total-currently-infected-linear', as_json=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bpang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\covid_daily\covid.py", line 168, in data
    raise RuntimeError("Information could not be retrieved since it is not available at Worldometers.info!")
RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!
>>> data = covid_daily.data(country='spain', chart='total-currently-infected-linear', as_json=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bpang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\covid_daily\covid.py", line 168, in data
    raise RuntimeError("Information could not be retrieved since it is not available at Worldometers.info!")
RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!
**>>> data = covid_daily.data(country='china', chart='total-currently-infected-linear', as_json=False)**
>>> data = covid_daily.data(country='cuba', chart='total-currently-infected-linear', as_json=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bpang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\covid_daily\covid.py", line 168, in data
    raise RuntimeError("Information could not be retrieved since it is not available at Worldometers.info!")
RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!
>>> data = covid_daily.data(country='us', chart='total-currently-infected-linear', as_json=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bpang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\covid_daily\covid.py", line 168, in data
    raise RuntimeError("Information could not be retrieved since it is not available at Worldometers.info!")
RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!

**Comment by BaoshanPang** [comment]
I think I find the problem:
the chart "total-currently-infected-linear" is not existed any more for many countries except for 'china'.
We need to use a different chart name in order to get the data. To get what charts are avaible, I use the wget command:
_$ wget "https://www.worldometers.info/coronavirus/country/us/"
--2021-05-07 21:08:12--  https://www.worldometers.info/coronavirus/country/us/
Resolving www.worldometers.info (www.worldometers.info)... 172.67.70.249, 104.26.4.2, 104.26.5.2, ...
Connecting to www.worldometers.info (www.worldometers.info)|172.67.70.249|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index.html'

     0K .......... .......... .......... .......... ..........  879K
    50K .......... .......... .......... .......... .......... 1.40M
   100K .......... .......... .......... .......... .......... 2.61M
   150K .......... .......... .......... .......... .......... 4.21M
   200K .......... .......... .......... .......... .......... 4.18M
   250K .......... .......... .......... .......... .......... 3.09M
   300K .......... .......... .......... .......... .......... 4.24M
   350K .......... .......... ........                         2.99M=0.2s

2021-05-07 21:08:13 (2.17 MB/s) - 'index.html' saved [387305]_

Then search "Highcharts.chart" in the download file index.html:

$ grep Highcharts.chart index.html
    Highcharts.chart('deaths-cured-outcome-small', {
    Highcharts.chart('coronavirus-cases-linear', {
    Highcharts.chart('coronavirus-cases-log', {
    Highcharts.chart('graph-cases-daily', {
    Highcharts.chart('graph-active-cases-total', {
    Highcharts.chart('coronavirus-deaths-linear', {
    Highcharts.chart('coronavirus-deaths-log', {
    Highcharts.chart('graph-deaths-daily', {

**Comment by esinkei** [comment]
---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-34-bf4fae0e22df> in <module>()
      1 for idx, available_chart in enumerate(AVAILABLE_CHARTS):
----> 2     data = covid_daily.data(country='spain', chart=available_chart, as_json=False)
      3     data.plot(ax=axs[pairs[idx]], title=available_chart)
      4 
      5 fig.tight_layout()

/usr/local/lib/python3.7/dist-packages/covid_daily/covid.py in data(country, chart, as_json)
    166 
    167     if not flag:
--> 168         raise RuntimeError("Information could not be retrieved since it is not available at Worldometers.info!")
    169 
    170     return data

RuntimeError: Information could not be retrieved since it is not available at Worldometers.info!
